### ISSUE TITLE
Selection breaks if interrupted

### ISSUE THREAD

**Issue by HenryWilder** [HenryWilder/passion-projects#31]
Hovering any pane can cause selection to stop working correctly.

**Comment by AmityWilder** [comment]
It appears that the bug doesn't happen when selection is interrupted, but when selection events (such as buttons being released) occur without updating the mode.

**Comment by AmityWilder** [comment]
Resolved by changing the system so that, instead of disabling tool updates when hovering a panel, only the hover update itself gets disabled (while hovering a panel).
